"""Initial  migration

Revision ID: f9c6c173cfcb
Revises: fc16d5c0ff93
Create Date: 2024-06-03 23:20:24.227488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c6c173cfcb'
down_revision: Union[str, None] = 'fc16d5c0ff93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
